### PR TITLE
FF

### PR DESCRIPTION
**Pull request by Yasir-siddiqui**

### CODE REVIEW

**Comment by krypticallusion** [comment]
@Yasir-siddiqui wtf

**Comment by ATechnoHazard** [comment]
Lelmeo, we can pull in shit ourselves

**Comment by abhijeetbohra** [comment]
@Yasir-siddiqui Sudo nahi milega. Thanks.

**Comment by ATechnoHazard** [comment]
Hueheuejuehueheueheu

**Comment by ATechnoHazard** [comment]
Hueheuejuehueheueheu

**Comment by krypticallusion** [comment]
We know how to **git pull**.
Thanks.

**Comment by Yasir-siddiqui** [comment]
;_; I exidently do this shit WTF !_!

**Comment by abhijeetbohra** [comment]
@sicrs #Exidently

**Pull request closed without merging**
